apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: cam-ibm-cam
    chart: ibm-cam-3.1.0
    heritage: Tiller
    release: cam
  name: cam-terraform-pv
  namespace: services
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  selector:
    matchLabels:
      type: cam-terraform
  storageClassName: ""
  volumeName: cam-terraform-pv