apiVersion: v1
entries:
  auth:
  - apiVersion: v1
    created: 2017-08-21T15:16:34.59058004-04:00
    description: BlueCompute Auth Microservice
    digest: 696396e2a572fc06b648d2f2c6e00b76190eddfcc8f829d395ec21099d0e9249
    name: auth
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/auth-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-08-21T15:16:34.590314634-04:00
    description: BlueCompute Auth Microservice
    digest: 055b4ab2fad15d874622b02e36ec973c789cd16beffc3baab8e966951fa49123
    name: auth
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/auth-0.1.0.tgz
    version: 0.1.0
  bluecompute:
  - apiVersion: v1
    created: 2017-08-21T15:16:34.593082117-04:00
    description: Bluecompute Application Chart
    digest: 449e568374078bf7da004489a1a9c563d18afe23083eb1a524881d39d4d50bc8
    name: bluecompute
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/bluecompute-0.0.1.tgz
    version: 0.0.1
  bluecompute-ce:
  - apiVersion: v1
    created: 2017-08-21T15:16:34.596285688-04:00
    description: Bluecompute Application Chart
    digest: 0732193fb0d3d2e2ed1459e55fa3afd461475a9cfc764f39e371474a735031f8
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/bluecompute-ce-0.0.1.tgz
    version: 0.0.1
  catalog:
  - apiVersion: v1
    created: 2017-08-21T15:16:34.597245586-04:00
    description: BlueCompute Catalog Microservice
    digest: ae68f8deca4c0c251cb3daa97a6ed75bc79a377c1a765297fe55be53a082a9f8
    name: catalog
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/catalog-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-08-21T15:16:34.596740366-04:00
    description: BlueCompute Catalog Microservice
    digest: 5943bf174fa59f6bffafb011c2d35349324907c6c105e0b2f05dea39c59869c1
    name: catalog
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/catalog-0.1.1.tgz
    version: 0.1.1
  customer:
  - apiVersion: v1
    created: 2017-08-21T15:16:34.598208188-04:00
    description: BlueCompute Customer Microservice
    digest: 36965bbf1d5b2086081cd587f3bca9a744350804efe828af8901ed81d2d9323c
    name: customer
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/customer-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-08-21T15:16:34.597634421-04:00
    description: BlueCompute Customer Microservice
    digest: c637de164bd9267688eddd122476551f84712cf14f55f2f0681cb20770b70b5b
    name: customer
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/customer-0.1.0.tgz
    version: 0.1.0
  grafana-bc:
  - created: 2017-08-21T15:16:34.598731574-04:00
    description: The leading tool for querying and visualizing time series and metrics.
    digest: 41e9b7e0e2532428ac273edf9ef0e0980199cf097dd9b76a9239045752a5c040
    engine: gotpl
    home: https://grafana.net
    icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
    maintainers:
    - email: zanhsieh@gmail.com
      name: Ming Hsieh
    - email: brobert@il.ibm.com
      name: Robert Barron
    name: grafana-bc
    sources:
    - https://github.com/grafana/grafana
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/grafana-bc-0.3.1.tgz
    version: 0.3.1
  ibmcase-bluemix-service:
  - apiVersion: v1
    created: 2017-08-21T15:16:34.598947654-04:00
    description: Deploy a service in Bluemix and bind to my cluster
    digest: a6b0320dbcb2bd79642bcc12424f423116e367c02dc2b0a2ebadb181b6cd90d8
    name: ibmcase-bluemix-service
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/ibmcase-bluemix-service-0.1.0.tgz
    version: 0.1.0
  ibmcase-couchdb:
  - apiVersion: v1
    created: 2017-08-21T15:16:34.599165786-04:00
    description: A Helm chart for Kubernetes
    digest: 38571a8d5651b245c662bc56a0a8f1d1110dbde0ea5c86286ace77615f2bd12e
    name: ibmcase-couchdb
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/ibmcase-couchdb-0.1.0.tgz
    version: 0.1.0
  ibmcase-elasticsearch:
  - apiVersion: v1
    created: 2017-08-21T15:16:34.5993384-04:00
    description: BlueCompute ElasticSearch for Catalog
    digest: d854bb5e3b269676cf68946c306c1e2c5c09bd974d37729f0cf649fc68f98853
    name: ibmcase-elasticsearch
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/ibmcase-elasticsearch-0.1.1.tgz
    version: 0.1.1
  ibmcase-mysql:
  - apiVersion: v1
    created: 2017-08-21T15:16:34.599573775-04:00
    description: resilient MySQL deployment
    digest: 12a1940fd55c716ef1c1511a9c9561eaa8a9fa4340e7ec3554404281442c0ac8
    name: ibmcase-mysql
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/ibmcase-mysql-0.1.0.tgz
    version: 0.1.0
  inventory:
  - apiVersion: v1
    created: 2017-08-21T15:16:34.600583036-04:00
    description: BlueCompute Inventory Microservice
    digest: a1a059d36a7a0ce13cb87cde0e739ca93bad1af03d1b934af524d712c2692078
    name: inventory
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/inventory-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-08-21T15:16:34.600075805-04:00
    description: BlueCompute Inventory Microservice
    digest: 27099b492c0de3ff363a2eafc79a823a14adf2f4ef1667ae7fad0b2b8287e1bf
    name: inventory
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/inventory-0.1.1.tgz
    version: 0.1.1
  orders:
  - apiVersion: v1
    created: 2017-08-21T15:16:34.601769126-04:00
    description: Bluecompute Orders Microservice
    digest: 208736f3a6f521a8df4412870c185eb94dc614f65913d8928d509c679d41e982
    name: orders
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/orders-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-08-21T15:16:34.60121097-04:00
    description: Bluecompute Orders Microservice
    digest: e80032e4c5cd126bfe542f55fcf53994c1728a4b4b52336fa93198c20b02718b
    name: orders
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/orders-0.1.0.tgz
    version: 0.1.0
  web:
  - apiVersion: v1
    created: 2017-08-21T15:16:34.602333924-04:00
    description: BlueCompute Web BFF app
    digest: 80ee89dfabfb44ced32d56d03e03cebdbbc2c4ca84f294189c01451b2f9516a7
    name: web
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/web-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-08-21T15:16:34.602056383-04:00
    description: BlueCompute Web BFF app
    digest: 578c75f83599b095fb0bd9e95034930442198c1e830dd4eea50c8cf62a460b15
    name: web
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/web-0.1.0.tgz
    version: 0.1.0
generated: 2017-08-21T15:16:34.589705871-04:00
