apiVersion: v1
entries:
  auth:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.766059636-04:00
    description: BlueCompute Auth Microservice
    digest: 887e0ed770fa7565fb3a348fe5ef1eb6d322bb5196a16635641cb635f25c90a4
    name: auth
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/auth-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-08-17T14:26:10.76541712-04:00
    description: BlueCompute Auth Microservice
    digest: 055b4ab2fad15d874622b02e36ec973c789cd16beffc3baab8e966951fa49123
    name: auth
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/auth-0.1.0.tgz
    version: 0.1.0
  bluecompute:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.770110506-04:00
    description: Bluecompute Application Chart
    digest: fe0ee6fa29c8031e6cedac408691bc229bb80efc5931acf47a39390d12a98bcc
    name: bluecompute
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/bluecompute-0.0.1.tgz
    version: 0.0.1
  bluecompute-ce:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.773824594-04:00
    description: Bluecompute Application Chart
    digest: 90d8b523db50bff82cf1de6476bfe5740b5c2ab9316ce680bb6fdab4622ffc32
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/bluecompute-ce-0.0.1.tgz
    version: 0.0.1
  catalog:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.776598337-04:00
    description: BlueCompute Catalog Microservice
    digest: 142de237d1c3ef2df1c8cc88834198a2d722c2552ac75b7372d31cde4daa5bc6
    name: catalog
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/catalog-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-08-17T14:26:10.775255813-04:00
    description: BlueCompute Catalog Microservice
    digest: 5943bf174fa59f6bffafb011c2d35349324907c6c105e0b2f05dea39c59869c1
    name: catalog
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/catalog-0.1.1.tgz
    version: 0.1.1
  catalog-elasticsearch:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.777373625-04:00
    description: BlueCompute ElasticSearch for Catalog
    digest: 4609239adaa130a790ba89f5a8472280d98b449571de3d2bf96252cb7ebd80db
    name: catalog-elasticsearch
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/catalog-elasticsearch-0.1.1.tgz
    version: 0.1.1
  customer:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.780064601-04:00
    description: BlueCompute Customer Microservice
    digest: 82893a44b532518a16e7c881d3357f7c756267394f793eac5e6efd67a51fe509
    name: customer
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/customer-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-08-17T14:26:10.77875896-04:00
    description: BlueCompute Customer Microservice
    digest: c637de164bd9267688eddd122476551f84712cf14f55f2f0681cb20770b70b5b
    name: customer
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/customer-0.1.0.tgz
    version: 0.1.0
  grafana-bc:
  - created: 2017-08-17T14:26:10.781275954-04:00
    description: The leading tool for querying and visualizing time series and metrics.
    digest: 41e9b7e0e2532428ac273edf9ef0e0980199cf097dd9b76a9239045752a5c040
    engine: gotpl
    home: https://grafana.net
    icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
    maintainers:
    - email: zanhsieh@gmail.com
      name: Ming Hsieh
    - email: brobert@il.ibm.com
      name: Robert Barron
    name: grafana-bc
    sources:
    - https://github.com/grafana/grafana
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/grafana-bc-0.3.1.tgz
    version: 0.3.1
  ibmcase-bluemix-service:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.781902285-04:00
    description: Deploy a service in Bluemix and bind to my cluster
    digest: a6b0320dbcb2bd79642bcc12424f423116e367c02dc2b0a2ebadb181b6cd90d8
    name: ibmcase-bluemix-service
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/ibmcase-bluemix-service-0.1.0.tgz
    version: 0.1.0
  ibmcase-couchdb:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.782483611-04:00
    description: A Helm chart for Kubernetes
    digest: 5d9911e08cc5ce63e0ca07c65c4af2a5e4c7c1036feaeeb9a15c771b46a529cc
    name: ibmcase-couchdb
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/ibmcase-couchdb-0.1.0.tgz
    version: 0.1.0
  ibmcase-elasticsearch:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.782970152-04:00
    description: BlueCompute ElasticSearch for Catalog
    digest: db6f093741ce315a4cbcced549703eb459e3de3e38c0dee20915175ea497e38b
    name: ibmcase-elasticsearch
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/ibmcase-elasticsearch-0.1.1.tgz
    version: 0.1.1
  ibmcase-mysql:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.783480863-04:00
    description: resilient MySQL deployment
    digest: d8edd2772a8cdeddb43c11ad7e96e1c80bb7fc669c80d50f9c66f0cebbeccb1b
    name: ibmcase-mysql
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/ibmcase-mysql-0.1.0.tgz
    version: 0.1.0
  inventory:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.785980677-04:00
    description: BlueCompute Inventory Microservice
    digest: c3f29786f4a09ee9571f3afaae3121bbfe789cd3a41eaa45af86bb82ca6c562b
    name: inventory
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/inventory-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-08-17T14:26:10.784727768-04:00
    description: BlueCompute Inventory Microservice
    digest: 27099b492c0de3ff363a2eafc79a823a14adf2f4ef1667ae7fad0b2b8287e1bf
    name: inventory
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/inventory-0.1.1.tgz
    version: 0.1.1
  inventory-mysql:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.786569781-04:00
    description: BlueCompute Inventory Microservice
    digest: 7fb0135e17de4a26e5594845094531552cbfbe21fe4ff906a8115d47af771710
    engine: gotpl
    name: inventory-mysql
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/inventory-mysql-0.1.1.tgz
    version: 0.1.1
  orders:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.78931275-04:00
    description: Bluecompute Orders Microservice
    digest: 63a89cc5137705730872816c4c1d2808edaa111ff90439f773f76bbe947fee55
    name: orders
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/orders-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-08-17T14:26:10.787804309-04:00
    description: Bluecompute Orders Microservice
    digest: e80032e4c5cd126bfe542f55fcf53994c1728a4b4b52336fa93198c20b02718b
    name: orders
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/orders-0.1.0.tgz
    version: 0.1.0
  web:
  - apiVersion: v1
    created: 2017-08-17T14:26:10.790544094-04:00
    description: BlueCompute Web BFF app
    digest: 5b85122646cd8e5509911e67c29144d86cc6ea56b94001d8970cec993741c318
    name: web
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/web-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-08-17T14:26:10.789977797-04:00
    description: BlueCompute Web BFF app
    digest: 578c75f83599b095fb0bd9e95034930442198c1e830dd4eea50c8cf62a460b15
    name: web
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/web-0.1.0.tgz
    version: 0.1.0
generated: 2017-08-17T14:26:10.763916605-04:00
