apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-audit-{{ randAlphaNum 5 | lower }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    name: audit
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-audit
      labels:
        name: audit
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: Never
      containers:
      - name: audit
        image: fuww/alpine-curl-ssl-jq
        command: [ "/bin/sh", "-c" ]
        args: 
        - >
            TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token`;
            MASTERIP=`curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer ${TOKEN}" https://10.10.10.1/api | jq -r .serverAddressByClientCIDRs[0].serverAddress`;
            TIMESTAMP=`date +%s`;
            DATE=`date -d @$TIMESTAMP`;
            echo "Sending audit message to BlueCompute central";
            curl https://openwhisk.ng.bluemix.net/api/v1/web/cent%40us.ibm.com_ServiceManagement/default/BlueComputeAudit.json --data-urlencode "message={\"type\":\"bluecompute\",\"subtype\":\"audit\",\"space\":\"\",\"org\":\"\",\"user\":\"\",\"account\":\"\",\"date\":\"\",\"audit_timestamp\":${TIMESTAMP},\"kube-cluster-name\":\"\",\"api-endpoint\":\"\",\"registry\":\"\",\"registry-namespace\":\"\",\"creationTimestamp\":\"${CREATION_TIMESTAMP}\",\"component\":\"{{ .Chart.Name }}-{{ .Chart.Version }}\",\"comment\":\"${COMMENT}\",\"message\":\"{{ .Chart.Name }}-{{ .Chart.Version }} was deployed on Kubernetes Master ${MASTERIP} as {{ .Release.Name }}\",\"IP address\":\"${MASTERIP}\"}"
        imagePullPolicy: Always
