apiVersion: v1
entries:
  auth:
  - apiVersion: v1
    created: 2018-07-24T11:51:03.370172-05:00
    description: A Helm chart for Kubernetes
    digest: 96927219d5580c37585a02bd5484f1f973777b67ac3cee1f084623ef76ebee32
    name: auth
    urls:
    - auth-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    created: 2018-07-24T11:51:03.369738-05:00
    description: A Helm chart for Kubernetes
    digest: ad9012aa3d5aa36337898f1649233207821df04c5fbe40948535cf4a4e493a8b
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: auth
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-auth/tree/microprofile
    urls:
    - auth-0.0.1.tgz
    version: 0.0.1
  catalog:
  - apiVersion: v1
    created: 2018-07-24T11:51:03.370954-05:00
    description: A Helm chart for Kubernetes
    digest: 1eeceb1e58a83337976c621d50f3f07f2bf2822989b303f5359715d85f45e00f
    name: catalog
    urls:
    - catalog-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    created: 2018-07-24T11:51:03.370471-05:00
    description: A Helm chart for Kubernetes
    digest: fef5a9e7b655ff093e3b19ae94b8656ce77bee95b48dd25545c58b5829af94bb
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: catalog
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-inventory/tree/microprofile/catalog
    urls:
    - catalog-0.0.1.tgz
    version: 0.0.1
  customer:
  - apiVersion: v1
    created: 2018-07-24T11:51:03.372063-05:00
    description: A Helm chart for Kubernetes
    digest: 321d67245c1f40573e1331eb9718ecf65acb408944b58517c8cc2f244d1d0b1c
    name: customer
    urls:
    - customer-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    created: 2018-07-24T11:51:03.371586-05:00
    description: A Helm chart for Kubernetes
    digest: 91088c04a25f7228e5b6282ffb569f608aeccb396394b5eb12bb694ada3d0d59
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: customer
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-customer/tree/microprofile
    urls:
    - customer-0.0.1.tgz
    version: 0.0.1
  ibm-icpmonitoring:
  - created: 2018-07-24T11:51:03.377091-05:00
    description: IBM monitoring service in private cloud
    digest: 68a32d65a8a37663fe5892f76258c69f1491f51dfb61365205fd2cc08c5c566d
    engine: gotpl
    keywords:
    - IcpClusterResource
    - ICP
    - amd64
    - ppc64le
    - OpenSource
    name: ibm-icpmonitoring
    sources:
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    - https://github.com/grafana/grafana
    - https://github.com/prometheus/collectd_exporter
    - https://github.com/justwatchcom/elasticsearch_exporter
    tillerVersion: '>=2.7.0'
    urls:
    - ibm-icpmonitoring-1.1.0.tgz
    version: 1.1.0
  ibmcase-elasticsearch:
  - apiVersion: v1
    created: 2018-07-24T11:51:03.378168-05:00
    description: ElasticSearch
    digest: 0a28e3587dad578fe58636011804b733a2a7a8b894eae460f2ea9534071307bf
    icon: https://static-www.elastic.co/assets/blt9a26f88bfbd20eb5/icon-elasticsearch-bb.svg
    name: ibmcase-elasticsearch
    urls:
    - ibmcase-elasticsearch-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2018-07-24T11:51:03.377607-05:00
    description: ElasticSearch
    digest: 49f994fc02e8d512568a538da380cb97bffcb6ae6637caead8703414fbc27d62
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    icon: https://static-www.elastic.co/assets/blt9a26f88bfbd20eb5/icon-elasticsearch-bb.svg
    name: ibmcase-elasticsearch
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-inventory/tree/microprofile/catalog/chart/ibmcase-elasticsearch
    urls:
    - ibmcase-elasticsearch-0.0.1.tgz
    version: 0.0.1
  inventory:
  - apiVersion: v1
    created: 2018-07-24T11:51:03.37959-05:00
    description: A Helm chart for Kubernetes
    digest: 9f90c8d52271cdc5069685b268136de3b2970e014575a0490ec7ab5bde48ff2f
    name: inventory
    urls:
    - inventory-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    created: 2018-07-24T11:51:03.379178-05:00
    description: A Helm chart for Kubernetes
    digest: 9f943c34b0175e9ee8580ba08e3f2b92b451567c914f267df509509fca0507b8
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: inventory
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-inventory/tree/microprofile/inventory
    urls:
    - inventory-0.0.1.tgz
    version: 0.0.1
  inventorydb:
  - appVersion: 1.0.0
    created: 2018-07-24T11:51:03.381154-05:00
    description: Fast, reliable, scalable, and easy to use open-source relational
      database system.
    digest: e5227c599e062c3424fca60a60011c943af124cff800beef435581b39d837c34
    name: inventorydb
    urls:
    - inventorydb-1.0.0.tgz
    version: 1.0.0
  - appVersion: 1.0.0
    created: 2018-07-24T11:51:03.380414-05:00
    description: Fast, reliable, scalable, and easy to use open-source relational
      database system.
    digest: 9bd5579dce971a2a6457e246e08afaacbc2b71a6d74dfd0ccc2829ea89e4cc03
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: inventorydb
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-inventory/tree/microprofile/inventory/chart/inventorydb
    urls:
    - inventorydb-0.0.1.tgz
    version: 0.0.1
  keystore:
  - apiVersion: v1
    created: 2018-07-24T11:51:03.381917-05:00
    description: A Helm chart for keystore
    digest: 9ad390b66dd0730741d711f1a6d079f2cdb6e9839495d8f0aab1ee4cb0a62570
    name: keystore
    urls:
    - keystore-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    created: 2018-07-24T11:51:03.381551-05:00
    description: A Helm chart for keystore
    digest: 93f17eaacf9713c87b584fe2ad272d9e567ebf9c7d5eef5bd96bc39e7ccf6ef5
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: keystore
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile/Keystore
    urls:
    - keystore-0.0.1.tgz
    version: 0.0.1
  orders:
  - apiVersion: v1
    created: 2018-07-24T11:51:03.382889-05:00
    description: BlueCompute Orders Microservice
    digest: dc5f7ea7b0b6800df78fade5761a91782583f4620290605accf420ebc6925a31
    name: orders
    urls:
    - orders-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    created: 2018-07-24T11:51:03.382475-05:00
    description: BlueCompute Orders Microservice
    digest: 954c8215b1cbb34fcc6010804a98667b99b8fcae7d7e7c09741abd47edef7ebf
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: orders
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-orders/tree/microprofile
    urls:
    - orders-0.0.1.tgz
    version: 0.0.1
  ordersdb:
  - appVersion: 1.0.0
    created: 2018-07-24T11:51:03.384533-05:00
    description: Fast, reliable, scalable, and easy to use open-source relational
      database system.
    digest: 4c12c39de5c5c01096040fce976fba0d39784ffc2e71025fd6774dfe5452c6e8
    name: ordersdb
    urls:
    - ordersdb-1.0.0.tgz
    version: 1.0.0
  - appVersion: 1.0.0
    created: 2018-07-24T11:51:03.383679-05:00
    description: Fast, reliable, scalable, and easy to use open-source relational
      database system.
    digest: 4325d6b35fa88a4bb7ce0d9f60272c87bcfd284406af455636193b978bbfcb7e
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: ordersdb
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-orders/tree/microprofile/chart/ordersdb
    urls:
    - ordersdb-0.0.1.tgz
    version: 0.0.1
  web:
  - apiVersion: v1
    created: 2018-07-24T11:51:03.38558-05:00
    description: BlueCompute Web BFF app
    digest: 88ee12fb1d20347ed32ff5c2b0b99b216f74a9f0c652db51a0222eacfb96b109
    name: web
    urls:
    - web-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    created: 2018-07-24T11:51:03.385061-05:00
    description: BlueCompute Web BFF app
    digest: 349fa15b77dbd01b98b82b895007ae47e17bca94860b665b6128cd2447e18d1e
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: web
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-bluecompute-web/tree/microprofile
    urls:
    - web-0.0.1.tgz
    version: 0.0.1
  zipkin:
  - apiVersion: v1
    created: 2018-07-24T11:51:03.386-05:00
    description: A Helm chart for Zipkin
    digest: ebc5f9a83ac1f475a7a716149c20201782ab48789ec9adc63f87899961cf30e5
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: zipkin
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile/Zipkin
    urls:
    - zipkin-0.0.1.tgz
    version: 0.0.1
generated: 2018-07-24T11:51:03.366298-05:00
