version: '3'
services:
  inventory:
   build: ../../refarch-cloudnative-micro-inventory/inventory
   image: inventory:v1.0.0

  catalog:
   build: ../../refarch-cloudnative-micro-inventory/catalog
   image: catalog:v1.0.0

  orders:
   build: ../../refarch-cloudnative-micro-orders
   image: orders:v1.0.0

  customer:
   build: ../../refarch-cloudnative-micro-customer
   image: customer:v1.0.0

  auth:
   build: ../../refarch-cloudnative-auth
   image: auth:v1.0.0

  web:
   build: ../../refarch-cloudnative-bluecompute-web
   image: bc-web:v1.0.0

  keystore:
   build: ../Kube_Jobs
   image: keygen:latest
