dependencies:
  - name: auth
    version: 0.2.0
    #repository: https://fabiogomezdiaz.github.io/refarch-cloudnative-kubernetes/charts
    repository: http://localhost:8879
  - name: catalog
    version: 0.2.0
    #repository: https://fabiogomezdiaz.github.io/refarch-cloudnative-kubernetes/charts
    repository: http://localhost:8879
  - name: customer
    version: 0.2.0
    #repository: https://fabiogomezdiaz.github.io/refarch-cloudnative-kubernetes/charts
    repository: http://localhost:8879
  - name: inventory
    version: 0.2.0
    #repository: https://fabiogomezdiaz.github.io/refarch-cloudnative-kubernetes/charts
    repository: http://localhost:8879
  - name: orders
    version: 0.2.0
    #repository: https://fabiogomezdiaz.github.io/refarch-cloudnative-kubernetes/charts
    repository: http://localhost:8879
  - name: web
    version: 0.2.0
    #repository: https://fabiogomezdiaz.github.io/refarch-cloudnative-kubernetes/charts
    repository: http://localhost:8879
