# Declare variables to be passed into your templates.
global:
  hs256key:
    secret: E6526VJkKYhyTFRFMC0pTECpHcZ7TGcq8pKsVVgz9KtESVpheEO284qKzfzg8HpWNBPeHOxNGlyudUHi6i8tFQJXC8PiI48RUpMh23vPDLGD35pCM0417gf58z5xlmRNii56fwRCmIhhV7hDsm3KO2jRv4EBVz7HrYbzFeqI45CaStkMYNipzSm2duuer7zRdMjEKIdqsby0JfpQpykHmC5L6hxkX0BT7XWqztTr6xHCwqst26O0g8r7bXSYjp4a

auth-ce:
  image:
    pullPolicy: Always
    tag: dev

catalog-ce:
  image:
    pullPolicy: Always
    tag: dev

customer-ce:
  image:
    pullPolicy: Always
    tag: dev

inventory-ce:
  image:
    pullPolicy: Always
    tag: dev

orders-ce:
  image:
    pullPolicy: Always
    tag: dev

web-ce:
  cluster_name: Fabio
  image:
    pullPolicy: Always
    tag: dev
  region: eu-de