# Declare variables to be passed into your templates.
global:
  hs256key:
    secret: E6526VJkKYhyTFRFMC0pTECpHcZ7TGcq8pKsVVgz9KtESVpheEO284qKzfzg8HpWNBPeHOxNGlyudUHi6i8tFQJXC8PiI48RUpMh23vPDLGD35pCM0417gf58z5xlmRNii56fwRCmIhhV7hDsm3KO2jRv4EBVz7HrYbzFeqI45CaStkMYNipzSm2duuer7zRdMjEKIdqsby0JfpQpykHmC5L6hxkX0BT7XWqztTr6xHCwqst26O0g8r7bXSYjp4a

auth-ce:
  image:
    pullPolicy: Always
    tag: kube-int

catalog-ce:
  image:
    pullPolicy: Always
    tag: kube-int

customer-ce:
  image:
    pullPolicy: Always
    tag: kube-int

inventory-ce:
  image:
    pullPolicy: Always
    tag: kube-int

orders-ce:
  image:
    pullPolicy: Always
    tag: kube-int

web-ce:
  cluster_name: Fabio
  image:
    pullPolicy: Always
    tag: kube-int
  region: eu-de