apiVersion: batch/v1
kind: Job
metadata:
  name: keystoregen
spec:
  template:
    metadata:
      name: keystoregen
    spec:
      containers:
      - name: keystore
        image: keygen:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
        command: ["sh", "./bc_certs/keygen.sh"]
      restartPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
