apiVersion: v1
entries:
  bluecompute-ce:
  - apiVersion: v1
    created: 2018-09-27T17:33:59.387290778-05:00
    description: Bluecompute Application Chart
    digest: 5bc9301f7011270ef51d5813efddeab7bf7fc1543603144042b304d553e62f04
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce/bluecompute-ce-0.0.8.tgz
    version: 0.0.8
  - apiVersion: v1
    created: 2018-09-27T17:33:59.383078642-05:00
    description: Bluecompute Application Chart
    digest: a75b17096b5ba4a410cfb05479ea7ac08e2d9b1d0f58da55fea6edcad477f606
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce/bluecompute-ce-0.0.6.tgz
    version: 0.0.6
generated: 2018-09-27T17:33:59.378556353-05:00
