apiVersion: v1
entries:
  bluecompute-ce:
  - apiVersion: v1
    created: 2018-09-20T12:35:08.527265445-05:00
    description: Bluecompute Application Chart
    digest: 5bc9301f7011270ef51d5813efddeab7bf7fc1543603144042b304d553e62f04
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce/bluecompute-ce-0.0.8.tgz
    version: 0.0.8
  - apiVersion: v1
    created: 2018-09-20T12:35:08.52415441-05:00
    description: Bluecompute Application Chart
    digest: 31f80ebad5fa4005a02504c70ba19386ccb627dfc87a00c6a8ddf7ae7c5d1223
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce/bluecompute-ce-0.0.7.tgz
    version: 0.0.7
  - apiVersion: v1
    created: 2018-09-20T12:35:08.518828094-05:00
    description: Bluecompute Application Chart
    digest: a75b17096b5ba4a410cfb05479ea7ac08e2d9b1d0f58da55fea6edcad477f606
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce/bluecompute-ce-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v1
    created: 2018-09-20T12:35:08.514986278-05:00
    description: Bluecompute Application Chart
    digest: ad408ea385ae64492c05745e550a053765e3b51dfbfa4e629e17d220d3c56668
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce/bluecompute-ce-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v1
    created: 2018-09-20T12:35:08.5119926-05:00
    description: Bluecompute Application Chart
    digest: 8319d3a883008b387459b21d883f110fa2ba73a28a4c2144fea888849a09edab
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce/bluecompute-ce-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v1
    created: 2018-09-20T12:35:08.508966211-05:00
    description: Bluecompute Application Chart
    digest: f062029c5b56ef738327b30cc11458a8e645204c58bbf2fd05bc614e4c10767f
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce/bluecompute-ce-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    created: 2018-09-20T12:35:08.506592542-05:00
    description: Bluecompute Application Chart
    digest: f23647fb9829819ca7f27662acdad8891fc345323d49cd5597e643ffe6554afa
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce/bluecompute-ce-0.0.2.tgz
    version: 0.0.2
generated: 2018-09-20T12:35:08.503451691-05:00
