apiVersion: v1
entries:
  bluecompute-ce:
  - apiVersion: v1
    created: 2018-02-14T12:10:04.391742-05:00
    description: Bluecompute Application Chart
    digest: 626d10f4c5498a2919d3609f1a5ab16c6e9060b02a388b867c9da97acc469abb
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/bluecompute-ce/bluecompute-ce-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v1
    created: 2018-02-14T12:10:04.389945-05:00
    description: Bluecompute Application Chart
    digest: 8319d3a883008b387459b21d883f110fa2ba73a28a4c2144fea888849a09edab
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/bluecompute-ce/bluecompute-ce-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v1
    created: 2018-02-14T12:10:04.387445-05:00
    description: Bluecompute Application Chart
    digest: f062029c5b56ef738327b30cc11458a8e645204c58bbf2fd05bc614e4c10767f
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/bluecompute-ce/bluecompute-ce-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    created: 2018-02-14T12:10:04.384837-05:00
    description: Bluecompute Application Chart
    digest: f23647fb9829819ca7f27662acdad8891fc345323d49cd5597e643ffe6554afa
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/bluecompute-ce/bluecompute-ce-0.0.2.tgz
    version: 0.0.2
generated: 2018-02-14T12:10:04.382193-05:00
