apiVersion: v1
entries:
  bluecompute-ce:
  - apiVersion: v1
    created: 2018-01-03T13:54:18.059251-05:00
    description: Bluecompute Application Chart
    digest: d959a23ba450b7ed6804b1f39aa6247498819aa421b680e02e18c486e93cd53c
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/remove-dependency-charts/docs/charts/bluecompute-ce/bluecompute-ce-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    created: 2018-01-03T13:54:18.057548-05:00
    description: Bluecompute Application Chart
    digest: f23647fb9829819ca7f27662acdad8891fc345323d49cd5597e643ffe6554afa
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/remove-dependency-charts/docs/charts/bluecompute-ce/bluecompute-ce-0.0.2.tgz
    version: 0.0.2
generated: 2018-01-03T13:54:18.055107-05:00
