apiVersion: v1
entries:
  bluecompute-ce:
  - apiVersion: v1
    created: 2018-01-02T17:06:23.099713-05:00
    description: Bluecompute Application Chart
    digest: 270e88283b53f4b39b8c51f560f676a30432605a8b78b312185f9f41f24cfdbb
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/bluecompute-ce/bluecompute-ce-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    created: 2018-01-02T17:06:23.095841-05:00
    description: Bluecompute Application Chart
    digest: f23647fb9829819ca7f27662acdad8891fc345323d49cd5597e643ffe6554afa
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/jkwong888/refarch-cloudnative-kubernetes/master/docs/charts/bluecompute-ce/bluecompute-ce-0.0.2.tgz
    version: 0.0.2
generated: 2018-01-02T17:06:23.092561-05:00
