apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    type: cam-logs
  name: cam-logs-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: cam-logs-pv
    namespace: services
  nfs:
    path: /storage/seclusters/stgcluster/campv/cam_logs
    server: 172.16.253.213
  persistentVolumeReclaimPolicy: Retain